### PR TITLE
Conditionnally replace private IPv4

### PR DESCRIPTION
**Pull request by drzraf**
This does not lead to a significant processing time reduction though

### CODE REVIEW

**Comment by lpirl** [comment]
Thank you very much for your contribution @drzraf . I'd have some subjective suggestions regarding code readability. Would you be okay with me merging your changes and altering the code to my liking? Alternatively, I could express my suggestions in review comments, so we can discuss and you can incorporate suggestions yourself.

**Comment by drzraf** [comment]
Please alter as you need, of course.

**Comment by lpirl** [comment]
great, thanks again

**Comment by lpirl** [comment]
@drzraf I also mirrored your commit to [gitlab.com/lpirl/gdprify-log](https://gitlab.com/lpirl/gdprify-log), which is the standalone repository for this script.

**Pull request merged**
